on:
  push:
    branches:
      - staging
name: 🚀 Deploy to Staging
jobs:
  environment: Staging

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.STAGE_SERVER_IP }}
        username: ${{ secrets.STAGE_SERVER_USERNAME }}
        password: ${{ secrets.STAGE_SERVER_PASSOWRD }}
        server-dir: /webapp/
        exclude: |
          **/.git*
          **/.git*/**
          vendor/**
