on:
  push:
    branches:
      - production
name: 🚀 Deploy to Production
jobs:

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    environment: Production

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.PROD_SERVER_IP }}
        username: ${{ secrets.PROD_SERVER_USERNAME }}
        password: ${{ secrets.PROD_SERVER_PASSWORD }}
        server-dir: /webapp/
        exclude: |
          **/.git*
          **/.git*/**
          vendor/**
