on:
  push:
    branches:
      - staging
name: 🚀 Deploy to Staging

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    # Specify the environment here
    environment: Staging

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.STAGE_SERVER_IP }}
          username: ${{ secrets.STAGE_SERVER_USERNAME }}
          password: ${{ secrets.STAGE_SERVER_PASSWORD }}
          server-dir: /webapp/
          exclude: |
            **/.git*
            **/.git*/**
            vendor/**