on:
  push:
    branches:
      - production
name: 🚀 Deploy to Production
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: premium236.web-hosting.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /vms-ks.com/
        exclude: |
          **/.git*
          **/.git*/**
          **/vendor/**
